### ISSUE TITLE
salt-bootstrap broken against Amazon Linux

### ISSUE THREAD

**Issue by MarkuzK** [saltstack/salt-bootstrap#103]
Hi,

It seems that salt-bootstrap is broken on Amazon Linux since late last week (I tested on the newly release Amazon Linux AMI image as well as the previous one):

```
> sudo sh ./bootstrap-salt.sh -M -S -N

 *  INFO: sh ./bootstrap-salt.sh -- Version 1.5.2
 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.4.37-40.44.amzn1.x86_64
 *  INFO:   Distribution: Amazon Linux AMI 2013.03
...
Setting up Install Process
Package PyYAML-3.10-3.6.amzn1.x86_64 already installed and latest version
Package m2crypto-0.20.2-9.10.amzn1.x86_64 already installed and latest version
No package python-msgpack available.
No package python-zmq available.
...
Error: Package: salt-0.14.0-1.el6.noarch (epel-testing)
           Requires: python-zmq
Error: Package: salt-0.14.0-1.el6.noarch (epel-testing)
           Requires: python-msgpack
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
 * ERROR: Failed to run install_amazon_linux_ami_stable()!!!
```

Salt 0.13.1 can still be installed via 'sudo yum --enablerepo=epel install salt-minion'.

Would be great to have an option to specify which salt version to install (via the bootstrap script) ...

Cheers,

```
  Markus
```

**Comment by MarkuzK** [comment]
If I get python-zmq and python-msgpack from epel first, I can then run the bootstrap script without any issues.

**Comment by MarkuzK** [comment]
salt, salt-minion, salt-master etc. have now all been moved from epel-testing to epel ... need to reflect those changes in the bootstrap script.

**Comment by s0undt3ch** [comment]
Thanks @MarkuzK. Fixed in develop.

**Comment by martinvich** [comment]
I cannot install salt-minion :

```
--> Finished Dependency Resolution
Error: Package: salt-0.15.3-1.el6.noarch (epel-testing)
           Requires: python-msgpack
Error: Package: salt-0.15.3-1.el6.noarch (epel-testing)
           Requires: python-zmq
```

on Amazon Linux AMI release 2013.03

**Comment by s0undt3ch** [comment]
@martinvich Thanks for the report, need to try that 2013.03 AMI

**Comment by s0undt3ch** [comment]
@martinvich you were using the latest bootstrap script? Can we see the full output of the bootstrap process, preferably also passing `-D`?

**Comment by martinvich** [comment]
I was trying to install it this way : 

```
 sudo yum -y groupinstall "Development Tools"
 sudo yum -y groupinstall "Development Libraries"
 sudo yum -y --enablerepo=epel-testing install salt-minion
```

and when I use latest bootstrap script:

[ec2-user@ip-XXX-XXX-XXX-XXX ~]$ sudo ./bootstrap-salt.sh -D
-  INFO: /bin/sh ./bootstrap-salt.sh -- Version 1.5.5
  -  INFO: System Information:
  -  INFO:   CPU:          GenuineIntel
  -  INFO:   CPU Arch:     x86_64
  -  INFO:   OS Name:      Linux
  -  INFO:   OS Version:   3.4.43-43.43.amzn1.x86_64
  -  INFO:   Distribution: AmazonAMI 2013.03
  -  INFO: Installing minion
  - DEBUG: install_amazonami_2013_stable_deps not found....
  - DEBUG: install_amazonami_2013_03_stable_deps not found....
  - DEBUG: install_amazonami_2013_deps not found....
  - DEBUG: install_amazonami_2013_03_deps not found....
  - DEBUG: install_amazonami_stable_deps not found....
  - DEBUG: install_amazonami_deps not found....
  - DEBUG: install_amazonami_2013_stable not found....
  - DEBUG: install_amazonami_2013_03_stable not found....
  - DEBUG: install_amazonami_stable not found....
  - DEBUG: install_amazonami_2013_stable_post not found....
  - DEBUG: install_amazonami_2013_03_stable_post not found....
  - DEBUG: install_amazonami_2013_post not found....
  - DEBUG: install_amazonami_2013_03_post not found....
  - DEBUG: install_amazonami_stable_post not found....
  - DEBUG: install_amazonami_post not found....
  - DEBUG: install_amazonami_2013_stable_restart_daemons not found....
  - DEBUG: install_amazonami_2013_03_stable_restart_daemons not found....
  - DEBUG: install_amazonami_2013_restart_daemons not found....
  - DEBUG: install_amazonami_2013_03_restart_daemons not found....
  - DEBUG: install_amazonami_stable_restart_daemons not found....
  - DEBUG: install_amazonami_restart_daemons not found....
  - DEBUG: daemons_running_amazonami_2013_stable not found....
  - DEBUG: daemons_running_amazonami_2013_03_stable not found....
  - DEBUG: daemons_running_amazonami_2013 not found....
  - DEBUG: daemons_running_amazonami_2013_03 not found....
  - DEBUG: daemons_running_amazonami_stable not found....
  - DEBUG: daemons_running_amazonami not found....
  -  INFO: Found function daemons_running
  - ERROR: No dependencies installation function found. Exiting...
  - DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe

Propably it's all about those missing dependencies : python-msgpack, pyhon-zmq

**Comment by s0undt3ch** [comment]
The issue is not missing deps, its Amazon Linux not being properly detected.

Oh and salt is now on epel not epel-testing.

**Comment by s0undt3ch** [comment]
@martinvich I failed to trigger your issue since the AMI I used, `ami-05355a6c`, was properly identified:

```
[ec2-user@ip-10-152-147-240 ~]$ sudo sh bs.sh
 *  INFO: sh bs.sh -- Version 1.5.5

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.4.43-43.43.amzn1.x86_64
 *  INFO:   Distribution: Amazon Linux AMI 2013.03

 *  INFO: Installing minion
 *  INFO: Found function install_amazon_linux_ami_deps
 *  INFO: Found function install_amazon_linux_ami_stable
 *  INFO: Found function install_amazon_linux_ami_stable_post
 *  INFO: Found function install_amazon_linux_ami_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_amazon_linux_ami_deps()
```

Which AMI are you using?

**Comment by s0undt3ch** [comment]
No response in a long time. Closing. Please reopen if need be.

**Comment by antonakv** [comment]
Doesn't work on latest Amazon Linux AMI 2015.03

**Comment by s0undt3ch** [comment]
Thank You for your report. We'll get it sorted out...

**Comment by antonakv** [comment]
```
       __|  __|_  )
       _|  (     /   Amazon Linux AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-ami/2015.03-release-notes/
[ec2-user@salt-stack ~]$ sudo su -
Last login: Tue Apr  7 10:07:22 UTC 2015 on pts/0
[root@salt-stack ~]# wget -O install_salt.sh https://bootstrap.saltstack.com
--2015-04-07 10:10:20--  https://bootstrap.saltstack.com/
Resolving bootstrap.saltstack.com (bootstrap.saltstack.com)... 162.242.141.13
Connecting to bootstrap.saltstack.com (bootstrap.saltstack.com)|162.242.141.13|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
--2015-04-07 10:10:20--  https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.75.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.75.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 188799 (184K) [text/plain]
Saving to: ‘install_salt.sh’

install_salt.sh                          100%[=================================================================================>] 184.37K  --.-KB/s   in 0.1s   

2015-04-07 10:10:20 (1.30 MB/s) - ‘install_salt.sh’ saved [188799/188799]

[root@salt-stack ~]# sh install_salt.sh
 *  INFO: sh install_salt.sh -- Version 2015.03.15

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.14.35-28.38.amzn1.x86_64
 *  INFO:   Distribution: Amazon Linux AMI 2015.03

 *  INFO: Installing minion
 *  INFO: Found function install_amazon_linux_ami_deps
 *  INFO: Found function install_amazon_linux_ami_stable
 *  INFO: Found function install_amazon_linux_ami_stable_post
 *  INFO: Found function install_amazon_linux_ami_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_amazon_linux_ami_deps()
Retrieving http://mirrors.kernel.org/fedora-epel/6/x86_64/epel-release-6-8.noarch.rpm
Preparing...                          ########################################
Updating / installing...
epel-release-6-8                      ########################################
Cleaning up / removing...
epel-release-6-8.9.amzn1              ########################################
Loaded plugins: priorities, update-motd, upgrade-helper
975 packages excluded due to repository priority protections
Package python-ordereddict is obsoleted by python26-ordereddict, trying to install python26-ordereddict-1.1-2.5.amzn1.noarch instead
Package python-requests is obsoleted by python26-requests, trying to install python26-requests-1.2.3-5.10.amzn1.noarch instead
Resolving Dependencies
--> Running transaction check
---> Package python-msgpack.x86_64 0:0.4.4-2.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: python-msgpack-0.4.4-2.el6.x86_64
--> Processing Dependency: libpython2.6.so.1.0()(64bit) for package: python-msgpack-0.4.4-2.el6.x86_64
---> Package python-zmq.x86_64 0:14.3.1-1.el6 will be installed
---> Package python26-PyYAML.x86_64 0:3.10-3.10.amzn1 will be installed
---> Package python26-crypto.x86_64 0:2.6.1-1.10.amzn1 will be installed
---> Package python26-jinja2.noarch 0:2.7.2-2.15.amzn1 will be installed
--> Processing Dependency: python26-markupsafe for package: python26-jinja2-2.7.2-2.15.amzn1.noarch
--> Processing Dependency: python26-babel for package: python26-jinja2-2.7.2-2.15.amzn1.noarch
---> Package python26-m2crypto.x86_64 0:0.21.1-15.14.amzn1 will be installed
---> Package python26-ordereddict.noarch 0:1.1-2.5.amzn1 will be installed
---> Package python26-requests.noarch 0:1.2.3-5.10.amzn1 will be installed
--> Processing Dependency: python26-urllib3 >= 1.7 for package: python26-requests-1.2.3-5.10.amzn1.noarch
--> Processing Dependency: python26-chardet for package: python26-requests-1.2.3-5.10.amzn1.noarch
--> Running transaction check
---> Package python26.x86_64 0:2.6.9-1.80.amzn1 will be installed
---> Package python26-babel.noarch 0:0.9.4-5.1.8.amzn1 will be installed
--> Processing Dependency: python26-setuptools for package: python26-babel-0.9.4-5.1.8.amzn1.noarch
---> Package python26-chardet.noarch 0:2.0.1-7.7.amzn1 will be installed
---> Package python26-libs.x86_64 0:2.6.9-1.80.amzn1 will be installed
---> Package python26-markupsafe.x86_64 0:0.11-4.6.amzn1 will be installed
---> Package python26-urllib3.noarch 0:1.8.2-1.5.amzn1 will be installed
--> Processing Dependency: python26-backports-ssl_match_hostname for package: python26-urllib3-1.8.2-1.5.amzn1.noarch
--> Processing Dependency: python26-six for package: python26-urllib3-1.8.2-1.5.amzn1.noarch
--> Running transaction check
---> Package python26-backports-ssl_match_hostname.noarch 0:3.4.0.2-1.12.amzn1 will be installed
--> Processing Dependency: python26-backports for package: python26-backports-ssl_match_hostname-3.4.0.2-1.12.amzn1.noarch
---> Package python26-setuptools.noarch 0:12.2-1.30.amzn1 will be installed
---> Package python26-six.noarch 0:1.8.0-1.23.amzn1 will be installed
--> Running transaction check
---> Package python26-backports.x86_64 0:1.0-3.14.amzn1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================

Package                           Arch   Version            Repository    Size

================================================================================
Installing:
 python-msgpack                    x86_64 0.4.4-2.el6        epel          66 k
 python-zmq                        x86_64 14.3.1-1.el6       epel         467 k
 python26-PyYAML                   x86_64 3.10-3.10.amzn1    amzn-main    186 k
 python26-crypto                   x86_64 2.6.1-1.10.amzn1   amzn-main    697 k
 python26-jinja2                   noarch 2.7.2-2.15.amzn1   amzn-main    899 k
 python26-m2crypto                 x86_64 0.21.1-15.14.amzn1 amzn-main    542 k
 python26-ordereddict              noarch 1.1-2.5.amzn1      amzn-main    7.5 k
 python26-requests                 noarch 1.2.3-5.10.amzn1   amzn-main     94 k
Installing for dependencies:
 python26                          x86_64 2.6.9-1.80.amzn1   amzn-updates 5.7 M
 python26-babel                    noarch 0.9.4-5.1.8.amzn1  amzn-main    1.8 M
 python26-backports                x86_64 1.0-3.14.amzn1     amzn-main    5.2 k
 python26-backports-ssl_match_hostname
                                   noarch 3.4.0.2-1.12.amzn1 amzn-main     12 k
 python26-chardet                  noarch 2.0.1-7.7.amzn1    amzn-main    377 k
 python26-libs                     x86_64 2.6.9-1.80.amzn1   amzn-updates 692 k
 python26-markupsafe               x86_64 0.11-4.6.amzn1     amzn-main     27 k
 python26-setuptools               noarch 12.2-1.30.amzn1    amzn-updates 582 k
 python26-six                      noarch 1.8.0-1.23.amzn1   amzn-main     31 k
 python26-urllib3                  noarch 1.8.2-1.5.amzn1    amzn-main     98 k

Transaction Summary

================================================================================
Install  8 Packages (+10 Dependent packages)

Total download size: 12 M
Installed size: 39 M
Downloading packages:

--------------------------------------------------------------------------------
Total                                               13 MB/s |  12 MB  00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Warning: RPMDB altered outside of yum.
  Installing : python26-2.6.9-1.80.amzn1.x86_64                            1/18 
  Installing : python26-libs-2.6.9-1.80.amzn1.x86_64                       2/18 
  Installing : python26-ordereddict-1.1-2.5.amzn1.noarch                   3/18 
  Installing : python26-markupsafe-0.11-4.6.amzn1.x86_64                   4/18 
  Installing : python26-chardet-2.0.1-7.7.amzn1.noarch                     5/18 
  Installing : python26-six-1.8.0-1.23.amzn1.noarch                        6/18 
  Installing : python26-backports-1.0-3.14.amzn1.x86_64                    7/18 
  Installing : python26-backports-ssl_match_hostname-3.4.0.2-1.12.amzn1    8/18 
  Installing : python26-setuptools-12.2-1.30.amzn1.noarch                  9/18 
  Installing : python26-babel-0.9.4-5.1.8.amzn1.noarch                    10/18 
  Installing : python26-urllib3-1.8.2-1.5.amzn1.noarch                    11/18 
  Installing : python26-requests-1.2.3-5.10.amzn1.noarch                  12/18 
  Installing : python26-jinja2-2.7.2-2.15.amzn1.noarch                    13/18 
  Installing : python26-crypto-2.6.1-1.10.amzn1.x86_64                    14/18 
  Installing : python26-m2crypto-0.21.1-15.14.amzn1.x86_64                15/18 
  Installing : python26-PyYAML-3.10-3.10.amzn1.x86_64                     16/18 
  Installing : python-zmq-14.3.1-1.el6.x86_64                             17/18 
  Installing : python-msgpack-0.4.4-2.el6.x86_64                          18/18 
  Verifying  : python26-setuptools-12.2-1.30.amzn1.noarch                  1/18 
  Verifying  : python26-jinja2-2.7.2-2.15.amzn1.noarch                     2/18 
  Verifying  : python26-crypto-2.6.1-1.10.amzn1.x86_64                     3/18 
  Verifying  : python26-m2crypto-0.21.1-15.14.amzn1.x86_64                 4/18 
  Verifying  : python26-chardet-2.0.1-7.7.amzn1.noarch                     5/18 
  Verifying  : python26-six-1.8.0-1.23.amzn1.noarch                        6/18 
  Verifying  : python26-libs-2.6.9-1.80.amzn1.x86_64                       7/18 
  Verifying  : python26-babel-0.9.4-5.1.8.amzn1.noarch                     8/18 
  Verifying  : python26-ordereddict-1.1-2.5.amzn1.noarch                   9/18 
  Verifying  : python26-PyYAML-3.10-3.10.amzn1.x86_64                     10/18 
  Verifying  : python26-2.6.9-1.80.amzn1.x86_64                           11/18 
  Verifying  : python-zmq-14.3.1-1.el6.x86_64                             12/18 
  Verifying  : python-msgpack-0.4.4-2.el6.x86_64                          13/18 
  Verifying  : python26-requests-1.2.3-5.10.amzn1.noarch                  14/18 
  Verifying  : python26-backports-ssl_match_hostname-3.4.0.2-1.12.amzn1   15/18 
  Verifying  : python26-urllib3-1.8.2-1.5.amzn1.noarch                    16/18 
  Verifying  : python26-backports-1.0-3.14.amzn1.x86_64                   17/18 
  Verifying  : python26-markupsafe-0.11-4.6.amzn1.x86_64                  18/18 

Installed:
  python-msgpack.x86_64 0:0.4.4-2.el6                                           
  python-zmq.x86_64 0:14.3.1-1.el6                                              
  python26-PyYAML.x86_64 0:3.10-3.10.amzn1                                      
  python26-crypto.x86_64 0:2.6.1-1.10.amzn1                                     
  python26-jinja2.noarch 0:2.7.2-2.15.amzn1                                     
  python26-m2crypto.x86_64 0:0.21.1-15.14.amzn1                                 
  python26-ordereddict.noarch 0:1.1-2.5.amzn1                                   
  python26-requests.noarch 0:1.2.3-5.10.amzn1                                   

Dependency Installed:
  python26.x86_64 0:2.6.9-1.80.amzn1                                            
  python26-babel.noarch 0:0.9.4-5.1.8.amzn1                                     
  python26-backports.x86_64 0:1.0-3.14.amzn1                                    
  python26-backports-ssl_match_hostname.noarch 0:3.4.0.2-1.12.amzn1             
  python26-chardet.noarch 0:2.0.1-7.7.amzn1                                     
  python26-libs.x86_64 0:2.6.9-1.80.amzn1                                       
  python26-markupsafe.x86_64 0:0.11-4.6.amzn1                                   
  python26-setuptools.noarch 0:12.2-1.30.amzn1                                  
  python26-six.noarch 0:1.8.0-1.23.amzn1                                        
  python26-urllib3.noarch 0:1.8.2-1.5.amzn1                                     

Complete!
 *  INFO: Running install_amazon_linux_ami_stable()
Loaded plugins: priorities, update-motd, upgrade-helper
975 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package salt-minion.noarch 0:2014.7.1-1.el6 will be installed
--> Processing Dependency: salt = 2014.7.1-1.el6 for package: salt-minion-2014.7.1-1.el6.noarch
--> Running transaction check
---> Package salt.noarch 0:2014.7.1-1.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================

Package             Arch           Version                  Repository    Size

================================================================================
Installing:
 salt-minion         noarch         2014.7.1-1.el6           epel          23 k
Installing for dependencies:
 salt                noarch         2014.7.1-1.el6           epel         3.3 M

Transaction Summary

================================================================================
Install  1 Package (+1 Dependent package)

Total download size: 3.3 M
Installed size: 14 M
Downloading packages:

--------------------------------------------------------------------------------
Total                                               11 MB/s | 3.3 MB  00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : salt-2014.7.1-1.el6.noarch                                   1/2 
  Installing : salt-minion-2014.7.1-1.el6.noarch                            2/2 
  Verifying  : salt-minion-2014.7.1-1.el6.noarch                            1/2 
  Verifying  : salt-2014.7.1-1.el6.noarch                                   2/2 

Installed:
  salt-minion.noarch 0:2014.7.1-1.el6                                           

Dependency Installed:
  salt.noarch 0:2014.7.1-1.el6                                                  

Complete!
 *  INFO: Running install_amazon_linux_ami_stable_post()
 *  INFO: Running install_amazon_linux_ami_restart_daemons()
Starting salt-minion daemon: Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 6, in <module>
    from salt.scripts import salt_minion
ImportError: No module named salt.scripts
                                                           [FAILED]
 *  INFO: Running daemons_running()
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
```

**Comment by antonakv** [comment]
It seems that salt-bootstrap is broken on Amazon Linux quite frequently.
Puppet team looks on you with love :-)

**Comment by antonakv** [comment]
Actually Python 2.7 is default one in Amazon Linux 2015.03, not 2.6

**Comment by antonakv** [comment]
On development branch it just hangs on Git clone

```
[root@salt-stack ~]# sh install_salt.sh git develop
 *  INFO: sh install_salt.sh -- Version 2015.03.15

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.14.35-28.38.amzn1.x86_64
 *  INFO:   Distribution: Amazon Linux AMI 2015.03

 *  INFO: Installing minion
 *  INFO: Found function install_amazon_linux_ami_git_deps
 *  INFO: Found function install_amazon_linux_ami_git
 *  INFO: Found function install_amazon_linux_ami_git_post
 *  INFO: Found function install_amazon_linux_ami_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_amazon_linux_ami_git_deps()
Retrieving http://mirrors.kernel.org/fedora-epel/6/x86_64/epel-release-6-8.noarch.rpm
Preparing...                          ########################################
Updating / installing...
epel-release-6-8                      ########################################
Loaded plugins: priorities, update-motd, upgrade-helper
975 packages excluded due to repository priority protections
Package python-ordereddict is obsoleted by python26-ordereddict, trying to install python26-ordereddict-1.1-2.5.amzn1.noarch instead
Package python-requests is obsoleted by python26-requests, trying to install python26-requests-1.2.3-5.10.amzn1.noarch instead
Resolving Dependencies
--> Running transaction check
---> Package python-msgpack.x86_64 0:0.4.4-2.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: python-msgpack-0.4.4-2.el6.x86_64
--> Processing Dependency: libpython2.6.so.1.0()(64bit) for package: python-msgpack-0.4.4-2.el6.x86_64
---> Package python-zmq.x86_64 0:14.3.1-1.el6 will be installed
---> Package python26-PyYAML.x86_64 0:3.10-3.10.amzn1 will be installed
---> Package python26-crypto.x86_64 0:2.6.1-1.10.amzn1 will be installed
---> Package python26-jinja2.noarch 0:2.7.2-2.15.amzn1 will be installed
--> Processing Dependency: python26-markupsafe for package: python26-jinja2-2.7.2-2.15.amzn1.noarch
--> Processing Dependency: python26-babel for package: python26-jinja2-2.7.2-2.15.amzn1.noarch
---> Package python26-m2crypto.x86_64 0:0.21.1-15.14.amzn1 will be installed
---> Package python26-ordereddict.noarch 0:1.1-2.5.amzn1 will be installed
---> Package python26-requests.noarch 0:1.2.3-5.10.amzn1 will be installed
--> Processing Dependency: python26-urllib3 >= 1.7 for package: python26-requests-1.2.3-5.10.amzn1.noarch
--> Processing Dependency: python26-chardet for package: python26-requests-1.2.3-5.10.amzn1.noarch
--> Running transaction check
---> Package python26.x86_64 0:2.6.9-1.80.amzn1 will be installed
---> Package python26-babel.noarch 0:0.9.4-5.1.8.amzn1 will be installed
--> Processing Dependency: python26-setuptools for package: python26-babel-0.9.4-5.1.8.amzn1.noarch
---> Package python26-chardet.noarch 0:2.0.1-7.7.amzn1 will be installed
---> Package python26-libs.x86_64 0:2.6.9-1.80.amzn1 will be installed
---> Package python26-markupsafe.x86_64 0:0.11-4.6.amzn1 will be installed
---> Package python26-urllib3.noarch 0:1.8.2-1.5.amzn1 will be installed
--> Processing Dependency: python26-backports-ssl_match_hostname for package: python26-urllib3-1.8.2-1.5.amzn1.noarch
--> Processing Dependency: python26-six for package: python26-urllib3-1.8.2-1.5.amzn1.noarch
--> Running transaction check
---> Package python26-backports-ssl_match_hostname.noarch 0:3.4.0.2-1.12.amzn1 will be installed
--> Processing Dependency: python26-backports for package: python26-backports-ssl_match_hostname-3.4.0.2-1.12.amzn1.noarch
---> Package python26-setuptools.noarch 0:12.2-1.30.amzn1 will be installed
---> Package python26-six.noarch 0:1.8.0-1.23.amzn1 will be installed
--> Running transaction check
---> Package python26-backports.x86_64 0:1.0-3.14.amzn1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                           Arch   Version            Repository    Size
================================================================================
Installing:
 python-msgpack                    x86_64 0.4.4-2.el6        epel          66 k
 python-zmq                        x86_64 14.3.1-1.el6       epel         467 k
 python26-PyYAML                   x86_64 3.10-3.10.amzn1    amzn-main    186 k
 python26-crypto                   x86_64 2.6.1-1.10.amzn1   amzn-main    697 k
 python26-jinja2                   noarch 2.7.2-2.15.amzn1   amzn-main    899 k
 python26-m2crypto                 x86_64 0.21.1-15.14.amzn1 amzn-main    542 k
 python26-ordereddict              noarch 1.1-2.5.amzn1      amzn-main    7.5 k
 python26-requests                 noarch 1.2.3-5.10.amzn1   amzn-main     94 k
Installing for dependencies:
 python26                          x86_64 2.6.9-1.80.amzn1   amzn-updates 5.7 M
 python26-babel                    noarch 0.9.4-5.1.8.amzn1  amzn-main    1.8 M
 python26-backports                x86_64 1.0-3.14.amzn1     amzn-main    5.2 k
 python26-backports-ssl_match_hostname
                                   noarch 3.4.0.2-1.12.amzn1 amzn-main     12 k
 python26-chardet                  noarch 2.0.1-7.7.amzn1    amzn-main    377 k
 python26-libs                     x86_64 2.6.9-1.80.amzn1   amzn-updates 692 k
 python26-markupsafe               x86_64 0.11-4.6.amzn1     amzn-main     27 k
 python26-setuptools               noarch 12.2-1.30.amzn1    amzn-updates 582 k
 python26-six                      noarch 1.8.0-1.23.amzn1   amzn-main     31 k
 python26-urllib3                  noarch 1.8.2-1.5.amzn1    amzn-main     98 k

Transaction Summary
================================================================================
Install  8 Packages (+10 Dependent packages)

Total download size: 12 M
Installed size: 39 M
Downloading packages:
--------------------------------------------------------------------------------
Total                                               13 MB/s |  12 MB  00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python26-2.6.9-1.80.amzn1.x86_64                            1/18 
  Installing : python26-libs-2.6.9-1.80.amzn1.x86_64                       2/18 
  Installing : python26-ordereddict-1.1-2.5.amzn1.noarch                   3/18 
  Installing : python26-markupsafe-0.11-4.6.amzn1.x86_64                   4/18 
  Installing : python26-chardet-2.0.1-7.7.amzn1.noarch                     5/18 
  Installing : python26-six-1.8.0-1.23.amzn1.noarch                        6/18 
  Installing : python26-backports-1.0-3.14.amzn1.x86_64                    7/18 
  Installing : python26-backports-ssl_match_hostname-3.4.0.2-1.12.amzn1    8/18 
  Installing : python26-setuptools-12.2-1.30.amzn1.noarch                  9/18 
  Installing : python26-babel-0.9.4-5.1.8.amzn1.noarch                    10/18 
  Installing : python26-urllib3-1.8.2-1.5.amzn1.noarch                    11/18 
  Installing : python26-requests-1.2.3-5.10.amzn1.noarch                  12/18 
  Installing : python26-jinja2-2.7.2-2.15.amzn1.noarch                    13/18 
  Installing : python26-crypto-2.6.1-1.10.amzn1.x86_64                    14/18 
  Installing : python26-m2crypto-0.21.1-15.14.amzn1.x86_64                15/18 
  Installing : python26-PyYAML-3.10-3.10.amzn1.x86_64                     16/18 
  Installing : python-zmq-14.3.1-1.el6.x86_64                             17/18 
  Installing : python-msgpack-0.4.4-2.el6.x86_64                          18/18 
  Verifying  : python26-setuptools-12.2-1.30.amzn1.noarch                  1/18 
  Verifying  : python26-jinja2-2.7.2-2.15.amzn1.noarch                     2/18 
  Verifying  : python26-crypto-2.6.1-1.10.amzn1.x86_64                     3/18 
  Verifying  : python26-m2crypto-0.21.1-15.14.amzn1.x86_64                 4/18 
  Verifying  : python26-chardet-2.0.1-7.7.amzn1.noarch                     5/18 
  Verifying  : python26-six-1.8.0-1.23.amzn1.noarch                        6/18 
  Verifying  : python26-libs-2.6.9-1.80.amzn1.x86_64                       7/18 
  Verifying  : python26-babel-0.9.4-5.1.8.amzn1.noarch                     8/18 
  Verifying  : python26-ordereddict-1.1-2.5.amzn1.noarch                   9/18 
  Verifying  : python26-PyYAML-3.10-3.10.amzn1.x86_64                     10/18 
  Verifying  : python26-2.6.9-1.80.amzn1.x86_64                           11/18 
  Verifying  : python-zmq-14.3.1-1.el6.x86_64                             12/18 
  Verifying  : python-msgpack-0.4.4-2.el6.x86_64                          13/18 
  Verifying  : python26-requests-1.2.3-5.10.amzn1.noarch                  14/18 
  Verifying  : python26-backports-ssl_match_hostname-3.4.0.2-1.12.amzn1   15/18 
  Verifying  : python26-urllib3-1.8.2-1.5.amzn1.noarch                    16/18 
  Verifying  : python26-backports-1.0-3.14.amzn1.x86_64                   17/18 
  Verifying  : python26-markupsafe-0.11-4.6.amzn1.x86_64                  18/18 

Installed:
  python-msgpack.x86_64 0:0.4.4-2.el6                                           
  python-zmq.x86_64 0:14.3.1-1.el6                                              
  python26-PyYAML.x86_64 0:3.10-3.10.amzn1                                      
  python26-crypto.x86_64 0:2.6.1-1.10.amzn1                                     
  python26-jinja2.noarch 0:2.7.2-2.15.amzn1                                     
  python26-m2crypto.x86_64 0:0.21.1-15.14.amzn1                                 
  python26-ordereddict.noarch 0:1.1-2.5.amzn1                                   
  python26-requests.noarch 0:1.2.3-5.10.amzn1                                   

Dependency Installed:
  python26.x86_64 0:2.6.9-1.80.amzn1                                            
  python26-babel.noarch 0:0.9.4-5.1.8.amzn1                                     
  python26-backports.x86_64 0:1.0-3.14.amzn1                                    
  python26-backports-ssl_match_hostname.noarch 0:3.4.0.2-1.12.amzn1             
  python26-chardet.noarch 0:2.0.1-7.7.amzn1                                     
  python26-libs.x86_64 0:2.6.9-1.80.amzn1                                       
  python26-markupsafe.x86_64 0:0.11-4.6.amzn1                                   
  python26-setuptools.noarch 0:12.2-1.30.amzn1                                  
  python26-six.noarch 0:1.8.0-1.23.amzn1                                        
  python26-urllib3.noarch 0:1.8.2-1.5.amzn1                                     

Complete!
Loaded plugins: priorities, update-motd, upgrade-helper
975 packages excluded due to repository priority protections
Package git-2.1.0-1.38.amzn1.x86_64 already installed and latest version
Nothing to do
 *  WARN: The git revision being installed does not match a Salt version tag. Shallow cloning disabled
Cloning into 'salt'...
```

**Comment by antonakv** [comment]
Was it fixed ?

**Comment by s0undt3ch** [comment]
A package fix is being done for stable installations. For git based installations, this is not fixed yet.

**Comment by ghost** [comment]
Amazon Linux is broken quite frequently ... take a close look at 2015.03's python26.

**Comment by A-merpact** [comment]
Amazon Linux, AMI 2015.09.1

Running command: sh install_salt.sh -P -M

 *  INFO: sh install_salt.sh -- Version 2015.11.09

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.14.48-33.39.amzn1.x86_64
 *  INFO:   Distribution: Amazon Linux AMI 2015.03

 *  INFO: Installing minion
 *  INFO: Installing master
 *  INFO: Found function install_amazon_linux_ami_deps
 *  INFO: Found function install_amazon_linux_ami_stable
 *  INFO: Found function install_amazon_linux_ami_stable_post
 *  INFO: Found function install_amazon_linux_ami_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_amazon_linux_ami_deps()
warning: /var/tmp/rpm-tmp.CY5QdD: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
Retrieving http://mirrors.kernel.org/fedora-epel/6/x86_64/epel-release-6-8.noarch.rpm
Preparing...                          ########################################
Updating / installing...
epel-release-6-8                      ########################################
Loaded plugins: priorities, update-motd, upgrade-helper
968 packages excluded due to repository priority protections
Package PyYAML-3.11-1.el7.x86_64 already installed and latest version
Package python26-m2crypto-0.21.1-15.14.amzn1.x86_64 already installed and latest version
Package python-crypto-2.6.1-1.el7.x86_64 is obsoleted by python26-crypto-2.6.1-1.12.amzn1.x86_64 which is already installed
Package python-msgpack-0.4.6-1.el7.x86_64 already installed and latest version
Package python-zmq-14.7.0-1.el7.x86_64 already installed and latest version
Package python-ordereddict-1.1-6.el7.noarch already installed and latest version
Package python-jinja2-2.7.2-2.el7.noarch is obsoleted by python26-jinja2-2.7.2-2.15.amzn1.noarch which is already installed
Package python-requests-1.1.0-8.el7.noarch is obsoleted by python26-requests-1.2.3-5.10.amzn1.noarch which is already installed
Nothing to do
 *  INFO: Running install_amazon_linux_ami_stable()
Loaded plugins: priorities, update-motd, upgrade-helper
968 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package salt-master.noarch 0:2015.8.1-1.el7 will be installed
--> Processing Dependency: salt = 2015.8.1-1.el7 for package: salt-master-2015.8.1-1.el7.noarch
--> Processing Dependency: systemd-python for package: salt-master-2015.8.1-1.el7.noarch
---> Package salt-minion.noarch 0:2015.8.1-1.el7 will be installed
--> Running transaction check
---> Package salt.noarch 0:2015.8.1-1.el7 will be installed
--> Processing Dependency: python-tornado >= 4.2.1 for package: salt-2015.8.1-1.el7.noarch
--> Processing Dependency: python-futures >= 2.0 for package: salt-2015.8.1-1.el7.noarch
--> Processing Dependency: systemd-units for package: salt-2015.8.1-1.el7.noarch
--> Processing Dependency: systemd-units for package: salt-2015.8.1-1.el7.noarch
--> Processing Dependency: systemd-python for package: salt-2015.8.1-1.el7.noarch
---> Package salt-master.noarch 0:2015.8.1-1.el7 will be installed
--> Processing Dependency: systemd-python for package: salt-master-2015.8.1-1.el7.noarch
--> Running transaction check
---> Package python-futures.noarch 0:3.0.3-1.el7 will be installed
---> Package python-tornado.x86_64 0:4.2.1-1.el7 will be installed
--> Processing Dependency: python-pycurl for package: python-tornado-4.2.1-1.el7.x86_64
---> Package salt.noarch 0:2015.8.1-1.el7 will be installed
--> Processing Dependency: systemd-units for package: salt-2015.8.1-1.el7.noarch
--> Processing Dependency: systemd-units for package: salt-2015.8.1-1.el7.noarch
--> Processing Dependency: systemd-python for package: salt-2015.8.1-1.el7.noarch
---> Package salt-master.noarch 0:2015.8.1-1.el7 will be installed
--> Processing Dependency: systemd-python for package: salt-master-2015.8.1-1.el7.noarch
--> Running transaction check
---> Package python26-pycurl.x86_64 0:7.19.0-17.12.amzn1 will be installed
---> Package salt.noarch 0:2015.8.1-1.el7 will be installed
--> Processing Dependency: systemd-units for package: salt-2015.8.1-1.el7.noarch
--> Processing Dependency: systemd-units for package: salt-2015.8.1-1.el7.noarch
--> Processing Dependency: systemd-python for package: salt-2015.8.1-1.el7.noarch
---> Package salt-master.noarch 0:2015.8.1-1.el7 will be installed
--> Processing Dependency: systemd-python for package: salt-master-2015.8.1-1.el7.noarch
--> Finished Dependency Resolution
Error: Package: salt-2015.8.1-1.el7.noarch (saltstack-repo)
           Requires: systemd-python
Error: Package: salt-master-2015.8.1-1.el7.noarch (saltstack-repo)
           Requires: systemd-python
Error: Package: salt-2015.8.1-1.el7.noarch (saltstack-repo)
           Requires: systemd-units
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
 * ERROR: Failed to run install_amazon_linux_ami_stable()!!!

**Comment by kai-zh** [comment]
Get following error on Amazon Linux 2015.9.1

Complete!
-  INFO: Running install_amazon_linux_ami_stable_post()
-  INFO: Running install_amazon_linux_ami_restart_daemons()
  Starting salt-minion daemon: [CRITICAL] Unable to import msgpack or msgpack_pure python modules
                                                         [  OK  ]
  Starting salt-master daemon: [CRITICAL] Unable to import msgpack or msgpack_pure python modules
  [ERROR   ] An un-handled exception was caught by salt's global exception handler:
  ImportError: No module named zmq
  Traceback (most recent call last):
  File "/usr/bin/salt-master", line 10, in <module>
    salt_master()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 50, in salt_master
    master.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 149, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 129, in prepare
    import salt.master
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 26, in <module>
    import zmq
  ImportError: No module named zmq
  Traceback (most recent call last):
  File "/usr/bin/salt-master", line 10, in <module>
    salt_master()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 50, in salt_master
    master.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 149, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 129, in prepare
    import salt.master
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 26, in <module>
    import zmq
  ImportError: No module named zmq
                                                         [FAILED]
-  INFO: Running daemons_running()
- ERROR: salt-master was not found running
- ERROR: Failed to run daemons_running()!!!
- ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
- ERROR: salt-master was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...

**Comment by wolfpackmars2** [comment]
Looking at the current develop version of the bootstrap, python-zmq package should have been installed.  As far as I can tell, the bootstrap finished the installation, but couldn't start the daemons.  In this case, it's either due to a problem with the salt code in master.py or that zmq was not installed.

https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L3758

If possible, try manually installing the python-zmq package and then trying to start the master daemon to see what errors occur.

**Comment by liquidblack** [comment]
Busted using both stable and develop version of code on recent 2015.11.09 Amazon AMI - this tested on a super vanilla, fresh as a daisy box

Initial digging looks related to how amazon is using priorities on their yum repos https://aws.amazon.com/amazon-linux-ami/faqs/

```
 *  INFO: -s sh -- Version 2015.11.09
 *  WARN: Running the unstable version of bootstrap-salt.sh

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.1.10-17.31.amzn1.x86_64
 *  INFO:   Distribution: Amazon Linux AMI 2015.09

 *  INFO: Installing minion
100  210k  100  210k    0     0   151k      0  0:00:01  0:00:01 --:--:--  436k
 *  INFO: Found function install_amazon_linux_ami_git_deps
 *  INFO: Found function install_amazon_linux_ami_git
 *  INFO: Found function install_amazon_linux_ami_git_post
 *  INFO: Found function install_amazon_linux_ami_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_amazon_linux_ami_git_deps()
warning: /var/tmp/rpm-tmp.ZYH9R6: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
Retrieving http://mirrors.kernel.org/fedora-epel/6/x86_64/epel-release-6-8.noarch.rpm
Preparing...                          ########################################
Updating / installing...
epel-release-6-8                      ########################################
Loaded plugins: priorities, update-motd, upgrade-helper
948 packages excluded due to repository priority protections
Package python-crypto is obsoleted by python26-crypto, trying to install python26-crypto-2.6.1-1.12.amzn1.x86_64 instead
Package python-ordereddict is obsoleted by python26, trying to install python26-2.6.9-2.84.amzn1.x86_64 instead
Resolving Dependencies
--> Running transaction check
---> Package PyYAML.x86_64 0:3.11-1.el7 will be installed
---> Package python-msgpack.x86_64 0:0.4.6-1.el7 will be installed
---> Package python-requests.noarch 0:2.6.0-1.el7 will be installed
--> Processing Dependency: python-urllib3 >= 1.10.2-1 for package: python-requests-2.6.0-1.el7.noarch
--> Processing Dependency: python-chardet >= 2.2.1-1 for package: python-requests-2.6.0-1.el7.noarch
---> Package python-zmq.x86_64 0:14.7.0-1.el7 will be installed
--> Processing Dependency: libzmq.so.4()(64bit) for package: python-zmq-14.7.0-1.el7.x86_64
---> Package python26.x86_64 0:2.6.9-2.84.amzn1 will be installed
--> Processing Dependency: libpython2.6.so.1.0()(64bit) for package: python26-2.6.9-2.84.amzn1.x86_64
---> Package python26-crypto.x86_64 0:2.6.1-1.12.amzn1 will be installed
---> Package python26-jinja2.noarch 0:2.7.2-2.15.amzn1 will be installed
--> Processing Dependency: python26-markupsafe for package: python26-jinja2-2.7.2-2.15.amzn1.noarch
--> Processing Dependency: python26-babel for package: python26-jinja2-2.7.2-2.15.amzn1.noarch
---> Package python26-m2crypto.x86_64 0:0.21.1-15.14.amzn1 will be installed
--> Running transaction check
---> Package python-requests.noarch 0:2.6.0-1.el7 will be installed
--> Processing Dependency: python-urllib3 >= 1.10.2-1 for package: python-requests-2.6.0-1.el7.noarch
--> Processing Dependency: python-chardet >= 2.2.1-1 for package: python-requests-2.6.0-1.el7.noarch
---> Package python26-babel.noarch 0:0.9.4-5.1.8.amzn1 will be installed
--> Processing Dependency: python26-setuptools for package: python26-babel-0.9.4-5.1.8.amzn1.noarch
---> Package python26-libs.x86_64 0:2.6.9-2.84.amzn1 will be installed
---> Package python26-markupsafe.x86_64 0:0.11-4.6.amzn1 will be installed
---> Package zeromq.x86_64 0:4.0.5-4.el7 will be installed
--> Running transaction check
---> Package python-requests.noarch 0:2.6.0-1.el7 will be installed
--> Processing Dependency: python-urllib3 >= 1.10.2-1 for package: python-requests-2.6.0-1.el7.noarch
--> Processing Dependency: python-chardet >= 2.2.1-1 for package: python-requests-2.6.0-1.el7.noarch
---> Package python26-setuptools.noarch 0:12.2-1.30.amzn1 will be installed
--> Processing Dependency: python26-backports-ssl_match_hostname for package: python26-setuptools-12.2-1.30.amzn1.noarch
--> Running transaction check
---> Package python-requests.noarch 0:2.6.0-1.el7 will be installed
--> Processing Dependency: python-urllib3 >= 1.10.2-1 for package: python-requests-2.6.0-1.el7.noarch
--> Processing Dependency: python-chardet >= 2.2.1-1 for package: python-requests-2.6.0-1.el7.noarch
---> Package python26-backports-ssl_match_hostname.noarch 0:3.4.0.2-1.12.amzn1 will be installed
--> Processing Dependency: python26-backports for package: python26-backports-ssl_match_hostname-3.4.0.2-1.12.amzn1.noarch
--> Running transaction check
---> Package python-requests.noarch 0:2.6.0-1.el7 will be installed
--> Processing Dependency: python-urllib3 >= 1.10.2-1 for package: python-requests-2.6.0-1.el7.noarch
--> Processing Dependency: python-chardet >= 2.2.1-1 for package: python-requests-2.6.0-1.el7.noarch
---> Package python26-backports.x86_64 0:1.0-3.14.amzn1 will be installed
--> Finished Dependency Resolution
Error: Package: python-requests-2.6.0-1.el7.noarch (saltstack-repo)
           Requires: python-chardet >= 2.2.1-1
           Available: python26-chardet-2.0.1-7.7.amzn1.noarch (amzn-main)
               python-chardet = 2.0.1-7.7.amzn1
Error: Package: python-requests-2.6.0-1.el7.noarch (saltstack-repo)
           Requires: python-urllib3 >= 1.10.2-1
           Available: python26-urllib3-1.8.2-1.5.amzn1.noarch (amzn-main)
               python-urllib3 = 1.8.2-1.5.amzn1
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
 * ERROR: Failed to run install_amazon_linux_ami_git_deps()!!!
```

**Comment by pwhack** [comment]
Getting the following error when using the 2015.11.09 version of the bootstrap script:
[failed_ec2_deploy.txt](https://github.com/saltstack/salt-bootstrap/files/133179/failed_ec2_deploy.txt)

The erroneous contents of /etc/yum.repos.d/saltstack-salt-epel-6.repo are:
[erroneous_repo_content.txt](https://github.com/saltstack/salt-bootstrap/files/133181/erroneous_repo_content.txt)

**Comment by rallytime** [comment]
@MarkuzK @martinvich @antonakv and others who have commented on this issue: I have fixed the problem with `git` installations on Amazon Linux with #906 (still waiting for merge), and I can now successfully bootstrap Amazon Linux with Salt with that change and recent versions of Salt.

Many updates have been made both to Salt packages (with the addition of repo.saltstack.com) and the corresponding fixes to the bootstrap script. I think once that change is merged in, this issue can be closed.

**Comment by rallytime** [comment]
Closing as #906 has been merged.

**Comment by Jakis** [comment]
Unfortunately, it seems like this is still an issue for a few amazon amis.  I'm seeing this with one of the most recent amazon linux amis, but also with an older one.  

Latest ami:
IMAGES	x86_64	2017-04-17T08:11:50.000Z	Amazon Linux AMI 2017.03.0.20170417 x86_64 HVM EBS	True	xen	ami-3234a652	amazon/amzn-ami-hvm-2017.03.0.20170417-x86_64-ebs	amazon	machine		amzn-ami-hvm-2017.03.0.20170417-x86_64-ebs	137112412989		True	/dev/xvda	ebs	simple	available	hvm

Salt-cloud debug excerpt:
--> Running transaction check
---> Package PyYAML27.x86_64 0:3.11-2.el6 will be installed
---> Package python27-msgpack.x86_64 0:0.4.6-2.el6 will be installed
---> Package python27-psutil.x86_64 0:5.2.2-1.ius.el6 will be installed
---> Package python27-zmq.x86_64 0:14.5.0-3.el6 wi
Connection to 10.2.0.250 closed.
[DEBUG   ] Connection to 10.2.0.250 closed.
ll be installed
--> Processing Dependency: libzmq.so.4()(64bit) for package: python27-zmq-14.5.0-3.el6.x86_64
---> Package salt.noarch 0:2017.7.1-1.el6 will be installed
--> Processing Dependency: python27-tornado >= 4.2.1 for package: salt-2017.7.1-1.el6.noarch
--> Running transaction check
---> Package salt.noarch 0:2017.7.1-1.el6 will be installed
--> Processing Dependency: python27-tornado >= 4.2.1 for package: salt-2017.7.1-1.el6.noarch
---> Package zeromq.x86_64 0:4.0.5-4.el6 will be installed
--> Finished Dependency Resolution
Error: Package: salt-2017.7.1-1.el6.noarch (saltstack-repo)
           Requires: python27-tornado >= 4.2.1
           Available: python27-tornado-2.2.1-7.8.amzn1.noarch (amzn-main)
               python27-tornado = 2.2.1-7.8.amzn1
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
 * ERROR: Failed to run install_amazon_linux_ami_stable()!!!
[DEBUG   ] ll be installed
--> Processing Dependency: libzmq.so.4()(64bit) for package: python27-zmq-14.5.0-3.el6.x86_64
---> Package salt.noarch 0:2017.7.1-1.el6 will be installed
--> Processing Dependency: python27-tornado >= 4.2.1 for package: salt-2017.7.1-1.el6.noarch
--> Running transaction check
---> Package salt.noarch 0:2017.7.1-1.el6 will be installed
--> Processing Dependency: python27-tornado >= 4.2.1 for package: salt-2017.7.1-1.el6.noarch
---> Package zeromq.x86_64 0:4.0.5-4.el6 will be installed
--> Finished Dependency Resolution
Error: Package: salt-2017.7.1-1.el6.noarch (saltstack-repo)
           Requires: python27-tornado >= 4.2.1
           Available: python27-tornado-2.2.1-7.8.amzn1.noarch (amzn-main)
               python27-tornado = 2.2.1-7.8.amzn1
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
 * ERROR: Failed to run install_amazon_linux_ami_stable()!!!
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oIdentitiesOnly=yes -oKbdInteractiveAuthentication=no -i /root/ssh-agent/keys/kuali-prod.1 -p 22 ec2-user@10.2.0.250 'sudo /tmp/.saltcloud-72bffc5d-066b-4d15-b120-26cc0b6bac05/deploy.sh -c '"'"'/tmp/.saltcloud-72bffc5d-066b-4d15-b120-26cc0b6bac05'"'"''' failed. Exit code: 1



I'm not using `script:`, just using the default bootstrap process.  I'm also seeing this same behavior with AMI:
IMAGES	x86_64	2014-10-08T02:10:49.000Z	Amazon Linux AMI 2014.09.1 x86_64 HVM EBS		xen	ami-b5a7ea85	amazon/amzn-ami-hvm-2014.09.1.x86_64-ebs	amazon	machine		amzn-ami-hvm-2014.09.1.x86_64-ebs	137112412989		True	/dev/xvda	ebs	simple	available	hvm

If I substitute the ami for ubuntu and change the ssh user, everything works great, so I think the issue is related to the Amazon Linux Ami.  Happy to gather more info if there's anything more I can get that might help.

/etc/salt# salt-cloud --version
salt-cloud 2017.7.1 (Nitrogen)
