### ISSUE TITLE
SALTSTACK-GPG-KEY.pub is missing in repo

### ISSUE THREAD

**Issue by AGirin** [saltstack/salt-bootstrap#1917]
bootstrap is falling to install onedir with the following error:

``` 
* ERROR: https://repo.saltproject.io/salt/py3/redhat/7/x86_64/latest/SALTSTACK-GPG-KEY.pub failed to download to /tmp/salt-gpg-YeFnBlbB.pub
* ERROR: Failed to run install_centos_onedir_deps()!!!
```

I see SALT-PROJECT-GPG-PUBKEY-2023.pub but no SALTSTACK-GPG-KEY.pub in the repo...

**Comment by garethgreenaway** [comment]
@AGirin Thanks for the report.  Can you give some details of what version of Salt you were attempting to install via the bootstrap, eg. provide the full call to the script.  Also, we just released a new version, can you please try that version and let us know if it resolves the issues for you?  Thanks!

**Comment by AGirin** [comment]
Latest version 3006... It somehow resolved itself in 2 days in bitbucket... But we are still getting this in yum:

`Downloading packages:
                    warning: /var/cache/yum/x86_64/7/saltstack/packages/salt-minion-3006.0-0.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 73d76b3f: NOKEY
                    Retrieving key from https://repo.saltproject.io/salt/py3/redhat/7/x86_64/latest/SALTSTACK-GPG-KEY.pub
`
And I just checked that repo - no suck key exists still...

**Comment by dmurphy18** [comment]
@AGirin  Closing this as fixed in release of the bootstrap 2024-07-12, see https://github.com/saltstack/salt-bootstrap/actions/workflows/ci.yml.  Please feel free to reopen if other matters relevant to this issue come to light.
