### ISSUE TITLE
No dependencies installation function found in bootstrap-salt-minion.sh

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt-bootstrap#22]
This issue is being migrated from saltstack/salt-cloud#248, originally reported by @mafrosis

```
Warning: Permanently added '10.143.6.178' (ECDSA) to the list of known hosts.
 * INFO: /tmp/deploy.sh -- Version 1.2
 * System Information:
     CPU:          GenuineIntel
     CPU Arch:     x86_64
     OS Name:      Linux
     OS Version:   3.2.0-32-virtual
     Distribution: Ubuntu 12.04
/tmp/deploy.sh: line 382: type: install_ubuntu_1204_stable_deps: not found
 * INFO: install_ubuntu_1204_stable_deps not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_1204_deps: not found
 * INFO: install_ubuntu_1204_deps not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_stable_deps: not found
 * INFO: install_ubuntu_stable_deps not found....
 * INFO: install_ubuntu_deps not found....
/tmp/deploy.sh: line 382: type: config_ubuntu_1204_stable_minion: not found
 * INFO: config_ubuntu_1204_stable_minion not found....
/tmp/deploy.sh: line 382: type: config_ubuntu_1204_minon: not found
 * INFO: config_ubuntu_1204_minon not found....
/tmp/deploy.sh: line 382: type: config_ubuntu_stable_minion: not found
 * INFO: config_ubuntu_stable_minion not found....
/tmp/deploy.sh: line 382: type: config_ubuntu_minion: not found
 * INFO: config_ubuntu_minion not found....
 * INFO: config_minion not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_1204_stable: not found
 * INFO: install_ubuntu_1204_stable not found....
 * INFO: install_ubuntu_stable not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_1204_stable_post: not found
 * INFO: install_ubuntu_1204_stable_post not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_1204_post: not found
 * INFO: install_ubuntu_1204_post not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_stable_post: not found
 * INFO: install_ubuntu_stable_post not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_post: not found
 * INFO: install_ubuntu_post not found....
 * ERROR: No dependencies installation function found. Exiting...
 * Removing the logging pipe /tmp/bootstrap-salt-minion.logpipe
Connection to 10.143.6.178 closed.
```

**Comment by inthecloud247** [comment]
reporting the same issue...

tried with:
`os: Ubuntu`

and

`os: python-bootstrap`

same errors.

**Comment by s0undt3ch** [comment]
@mafrosis got an IRC nick so I can talk to you on IRC?

**Comment by s0undt3ch** [comment]
I seem to be unable to reproduce your issue with the latest brootstrap script:

```
$ vagrant ssh
Welcome to Ubuntu 12.04.1 LTS (GNU/Linux 3.2.0-29-generic-pae i686)

 * Documentation:  https://help.ubuntu.com/
Last login: Sun Oct 21 15:16:59 2012 from 10.0.2.2

vagrant@ubuntu-12-04-1-server-i386:~$ sudo sh /salt/source/bootstrap-salt-minion.sh
 * INFO: /salt/source/bootstrap-salt-minion.sh -- Version 1.2
 * System Information:
     CPU:          GenuineIntel
     CPU Arch:     i686
     OS Name:      Linux
     OS Version:   3.2.0-29-generic-pae
     Distribution: Ubuntu 12.04
 * INFO: install_ubuntu_1204_stable_deps not found....
 * INFO: install_ubuntu_1204_deps not found....
 * INFO: install_ubuntu_stable_deps not found....
 * INFO: Found function install_ubuntu_deps
 * INFO: install_ubuntu_1204_stable not found....
 * INFO: Found function install_ubuntu_stable
 * INFO: install_ubuntu_1204_stable_post not found....
 * INFO: install_ubuntu_1204_post not found....
 * INFO: install_ubuntu_stable_post not found....
 * INFO: install_ubuntu_post not found....
 * Running install_ubuntu_deps()
Ign http://security.ubuntu.com precise-security InRelease

CTRL-C

vagrant@ubuntu-12-04-1-server-i386:~$ 
```

**Comment by s0undt3ch** [comment]
I know what this is:

```
vagrant@ubuntu-12-04-1-server-i386:~$ sudo bash /salt/source/bootstrap-salt-minion.sh
 * INFO: /salt/source/bootstrap-salt-minion.sh -- Version 1.2
 * System Information:
     CPU:          GenuineIntel
     CPU Arch:     i686
     OS Name:      Linux
     OS Version:   3.2.0-29-generic-pae
     Distribution: Ubuntu 12.04
/salt/source/bootstrap-salt-minion.sh: line 382: type: install_ubuntu_1204_stable_deps: not found
 * INFO: install_ubuntu_1204_stable_deps not found....
/salt/source/bootstrap-salt-minion.sh: line 382: type: install_ubuntu_1204_deps: not found
 * INFO: install_ubuntu_1204_deps not found....
/salt/source/bootstrap-salt-minion.sh: line 382: type: install_ubuntu_stable_deps: not found
 * INFO: install_ubuntu_stable_deps not found....
 * INFO: install_ubuntu_deps not found....
/salt/source/bootstrap-salt-minion.sh: line 382: type: install_ubuntu_1204_stable: not found
 * INFO: install_ubuntu_1204_stable not found....
 * INFO: install_ubuntu_stable not found....
/salt/source/bootstrap-salt-minion.sh: line 382: type: install_ubuntu_1204_stable_post: not found
 * INFO: install_ubuntu_1204_stable_post not found....
/salt/source/bootstrap-salt-minion.sh: line 382: type: install_ubuntu_1204_post: not found
 * INFO: install_ubuntu_1204_post not found....
/salt/source/bootstrap-salt-minion.sh: line 382: type: install_ubuntu_stable_post: not found
 * INFO: install_ubuntu_stable_post not found....
/salt/source/bootstrap-salt-minion.sh: line 382: type: install_ubuntu_post: not found
 * INFO: install_ubuntu_post not found....
 * ERROR: No dependencies installation function found. Exiting...
 * Removing the logging pipe /tmp/bootstrap-salt-minion.logpipe
 * Killing logging pipe tee's with pid(s): 5293
vagrant@ubuntu-12-04-1-server-i386:~$ 
```

**Comment by s0undt3ch** [comment]
@mafrosis, can you please show me the shebang line in your deploy.sh script please?

**Comment by s0undt3ch** [comment]
This issue was fixed in cf118fa7f89f6873fb8bda2ae7cbe1cbfef755da

**Comment by inthecloud247** [comment]
I tested https://github.com/saltstack/salt-bootstrap/commit/cf118fa7f89f6873fb8bda2ae7cbe1cbfef755da, and the issue still isn't fixed...

still get:

``` bash
 * INFO: /tmp/deploy.sh -- Version 1.2
 * System Information:
     CPU:          GenuineIntel
     CPU Arch:     x86_64
     OS Name:      Linux
     OS Version:   3.2.0-35-virtual
     Distribution: Ubuntu 12.04
/tmp/deploy.sh: line 382: type: install_ubuntu_1204_stable_deps: not found
 * INFO: install_ubuntu_1204_stable_deps not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_1204_deps: not found
 * INFO: install_ubuntu_1204_deps not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_stable_deps: not found
 * INFO: install_ubuntu_stable_deps not found....
 * INFO: install_ubuntu_deps not found....
/tmp/deploy.sh: line 382: type: config_ubuntu_1204_stable_minion: not found
 * INFO: config_ubuntu_1204_stable_minion not found....
/tmp/deploy.sh: line 382: type: config_ubuntu_1204_minon: not found
 * INFO: config_ubuntu_1204_minon not found....
/tmp/deploy.sh: line 382: type: config_ubuntu_stable_minion: not found
 * INFO: config_ubuntu_stable_minion not found....
/tmp/deploy.sh: line 382: type: config_ubuntu_minion: not found
 * INFO: config_ubuntu_minion not found....
 * INFO: config_minion not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_1204_stable: not found
 * INFO: install_ubuntu_1204_stable not found....
 * INFO: install_ubuntu_stable not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_1204_stable_post: not found
 * INFO: install_ubuntu_1204_stable_post not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_1204_post: not found
 * INFO: install_ubuntu_1204_post not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_stable_post: not found
 * INFO: install_ubuntu_stable_post not found....
/tmp/deploy.sh: line 382: type: install_ubuntu_post: not found
 * INFO: install_ubuntu_post not found....
 * ERROR: No dependencies installation function found. Exiting...
```

**Comment by s0undt3ch** [comment]
@ydavid365, if you're reporting an issue today, please try to use latest available from the git repository unless totally impossible. If you don't, I'll first ask you to update.

So, @ydavid365, could you please update to latest git a report back again the output? Thanks!

**Comment by inthecloud247** [comment]
@s0undt3ch Sure... before I test, I just want to confirm that I'm correctly specifying the bootstrap script that I want to deploy.

If I want to use the python-bootstrap script, should I be doing the following?

``` yaml
os: python-bootstrap
```

and should the 'old'-style `os` lines still work?

``` yaml
os: Ubuntu
```

Or is there a default and I don't really _need_ to specify anything at all?

**Comment by techhat** [comment]
The default in salt-cloud is now bootstrap-salt-minion.

If you still need to specify one, please switch os to script. I should also note that salt-cloud-specific configuration should be taken over to the salt-cloud issue tracker.

**Comment by inthecloud247** [comment]
k. I just needed to know what config to use for testing here. You just committed the docs for the new script option a few mins ago. :-)

**Comment by inthecloud247** [comment]
still doesn't seem to work...

I set the flag to `script: python-bootstrap` fyi...

``` bash
Warning: Permanently added '10.252.92.32' (ECDSA) to the list of known hosts.
sh: 1: /tmp: Permission denied
Connection to 10.252.92.32 closed.
[DEBUG   ] Executed /tmp/deploy.sh
[DEBUG   ] [chan 5] Max packet in: 34816 bytes
[DEBUG   ] [chan 5] Max packet out: 32768 bytes
[INFO    ] Secsh channel 5 opened.
[DEBUG   ] [chan 5] Sesch channel 5 request ok
[DEBUG   ] Removed /tmp/deploy.sh
[DEBUG   ] [chan 6] Max packet in: 34816 bytes
[DEBUG   ] [chan 6] Max packet out: 32768 bytes
[INFO    ] Secsh channel 6 opened.
[DEBUG   ] [chan 5] EOF sent (5)
[DEBUG   ] [chan 6] Sesch channel 6 request ok
[DEBUG   ] Removed /tmp/minion.pub
[DEBUG   ] [chan 7] Max packet in: 34816 bytes
[DEBUG   ] [chan 6] EOF sent (6)
[DEBUG   ] Ignoring message for dead channel 5
[DEBUG   ] Ignoring message for dead channel 5
[DEBUG   ] Ignoring message for dead channel 5
[DEBUG   ] [chan 7] Max packet out: 32768 bytes
[INFO    ] Secsh channel 7 opened.
[DEBUG   ] [chan 7] Sesch channel 7 request ok
[DEBUG   ] Removed /tmp/minion.pem
[DEBUG   ] [chan 8] Max packet in: 34816 bytes
[DEBUG   ] [chan 8] Max packet out: 32768 bytes
[INFO    ] Secsh channel 8 opened.
[DEBUG   ] [chan 7] EOF sent (7)
[DEBUG   ] [chan 8] Sesch channel 8 request ok
[DEBUG   ] Removed /tmp/minion
[DEBUG   ] SaltEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] EOF in transport thread
[INFO    ] Salt installed on test-domain.test.com
```

**Comment by inthecloud247** [comment]
I just confirmed that using the `script: Ubuntu` option does at least somewhat work... it downloads the packages etc. The ubuntu script doesn't finish properly, but I'll put that as an issue in the salt-cloud project...

this is on ubuntu 12.04-1 LTS:

``` bash
DEBUG   ] Uploading /tmp/deploy.sh to 10.253.92.156
[DEBUG   ] [chan 2] open('/tmp/deploy.sh', 'wb')
[DEBUG   ] [chan 2] open('/tmp/deploy.sh', 'wb') -> 00000000
[DEBUG   ] [chan 2] close(00000000)
[DEBUG   ] [chan 2] stat('/tmp/deploy.sh')
[DEBUG   ] [chan 4] Max packet in: 34816 bytes
[DEBUG   ] [chan 4] Max packet out: 32768 bytes
[INFO    ] Secsh channel 4 opened.
[DEBUG   ] [chan 4] Sesch channel 4 request ok
[DEBUG   ] Executing /tmp/deploy.sh
[DEBUG   ] Using sudo to run command
[DEBUG   ] Executing command: sudo bash /tmp/deploy.sh
[DEBUG   ] Using ssh command to simulate tty session, to execute command
[DEBUG   ] [chan 4] EOF received (4)
[DEBUG   ] [chan 4] EOF sent (4)
Warning: Permanently added '10.253.92.156' (ECDSA) to the list of known hosts.
deb http://ppa.launchpad.net/saltstack/salt/ubuntu precise main
OK
```

**Comment by s0undt3ch** [comment]
@ydavid365 It has been a huge day chasing [this](http://stackoverflow.com/questions/14447555/posix-compliant-way-to-see-if-a-function-is-defined-in-an-sh-script) down and still not having found a solution, so, please forgive me if I'm sounding rude, but, This Has Nothing To Do With Salt Bootstrap! You say it yourself!

```
I set the flag to script: python-bootstrap fyi...
```

Where in salt-bootstrap does one set that?

`salt-bootstrap` is a shell script.
It does not know anything about python, yaml, **salt-cloud** or anything else besides `sh`!

Ok?

**Comment by inthecloud247** [comment]
agreed! I'm just trying to present any information needed if you had difficulty reproducing the error. that's all.
