### ISSUE TITLE
Stable broken in 15.04 even with -P

### ISSUE THREAD

**Issue by DavidJFelix** [saltstack/salt-bootstrap#631]
I have tried this with and without the PIP flag, it get farthest with the PIP flag.

I run the following command:

 `curl -L https://bootstrap.saltstack.com | sudo sh -s -- -P`

And the output I get is mostly apt hits (scrollback lost) and ends with these errors:

```
Downloading/unpacking tornado>=4.0
  Running setup.py (path:/tmp/pip-build-4MHWhL/tornado/setup.py) egg_info for package tornado

    no previously-included directories found matching 'docs/build'
    warning: no files found matching 'tornado/test/README'
Downloading/unpacking backports.ssl-match-hostname (from tornado>=4.0)
  Downloading backports.ssl_match_hostname-3.4.0.2.tar.gz
  Running setup.py (path:/tmp/pip-build-4MHWhL/backports.ssl-match-hostname/setup.py) egg_info for package backports.ssl-match-hostname

Downloading/unpacking certifi (from tornado>=4.0)
Installing collected packages: tornado, backports.ssl-match-hostname, certifi
  Running setup.py install for tornado
    building 'tornado.speedups' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c tornado/speedups.c -o build/temp.linux-x86_64-2.7/tornado/speedups.o
    tornado/speedups.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    /tmp/pip-build-4MHWhL/tornado/setup.py:94: UserWarning:
    ********************************************************************
    WARNING: The tornado.speedups extension module could not
    be compiled. No C extensions are essential for Tornado to run,
    although they do result in significant speed improvements for
    websockets.
    The output above this warning shows how the compilation failed.

    Here are some hints for popular operating systems:

    If you are seeing this message on Linux you probably need to
    install GCC and/or the Python development package for your
    version of Python.

    Debian and Ubuntu users should issue the following command:

        $ sudo apt-get install build-essential python-dev

    RedHat, CentOS, and Fedora users should issue the following command:

        $ sudo yum install gcc python-devel

    If you are seeing this message on OSX please read the documentation
    here:

    http://api.mongodb.org/python/current/installation.html#osx
    ********************************************************************

      "The output above "
    command 'x86_64-linux-gnu-gcc' failed with exit status 1

    no previously-included directories found matching 'docs/build'
    warning: no files found matching 'tornado/test/README'
  Running setup.py install for backports.ssl-match-hostname

Successfully installed tornado backports.ssl-match-hostname certifi
Cleaning up...
Ign http://us-east-1.ec2.archive.ubuntu.com vivid InRelease
Ign http://us-east-1.ec2.archive.ubuntu.com vivid-updates InRelease
Hit http://us-east-1.ec2.archive.ubuntu.com vivid Release.gpg
Hit http://us-east-1.ec2.archive.ubuntu.com vivid-updates Release.gpg
Hit http://us-east-1.ec2.archive.ubuntu.com vivid Release
Hit http://us-east-1.ec2.archive.ubuntu.com vivid-updates Release
Ign http://security.ubuntu.com vivid-security InRelease
Hit http://security.ubuntu.com vivid-security Release.gpg
Hit http://us-east-1.ec2.archive.ubuntu.com vivid/main Sources
Hit http://us-east-1.ec2.archive.ubuntu.com vivid/universe Sources
Hit http://us-east-1.ec2.archive.ubuntu.com vivid/main amd64 Packages
Hit http://security.ubuntu.com vivid-security Release
Hit http://us-east-1.ec2.archive.ubuntu.com vivid/universe amd64 Packages
Hit http://us-east-1.ec2.archive.ubuntu.com vivid/main Translation-en
Hit http://us-east-1.ec2.archive.ubuntu.com vivid/universe Translation-en
Hit http://us-east-1.ec2.archive.ubuntu.com vivid-updates/main Sources
Hit http://us-east-1.ec2.archive.ubuntu.com vivid-updates/universe Sources
Hit http://us-east-1.ec2.archive.ubuntu.com vivid-updates/main amd64 Packages
Hit http://us-east-1.ec2.archive.ubuntu.com vivid-updates/universe amd64 Packages
Hit http://us-east-1.ec2.archive.ubuntu.com vivid-updates/main Translation-en
Hit http://us-east-1.ec2.archive.ubuntu.com vivid-updates/universe Translation-en
Ign http://ppa.launchpad.net vivid InRelease
Hit http://security.ubuntu.com vivid-security/main Sources
Hit http://security.ubuntu.com vivid-security/universe Sources
Hit http://security.ubuntu.com vivid-security/main amd64 Packages
Hit http://security.ubuntu.com vivid-security/universe amd64 Packages
Ign http://ppa.launchpad.net vivid InRelease
Hit http://security.ubuntu.com vivid-security/main Translation-en
Hit http://security.ubuntu.com vivid-security/universe Translation-en
Ign http://ppa.launchpad.net vivid InRelease
Ign http://ppa.launchpad.net vivid Release.gpg
Ign http://ppa.launchpad.net vivid Release.gpg
Hit http://ppa.launchpad.net vivid Release.gpg
Ign http://ppa.launchpad.net vivid Release
Ign http://ppa.launchpad.net vivid Release
Hit http://ppa.launchpad.net vivid Release
Hit http://ppa.launchpad.net vivid/main amd64 Packages
Hit http://ppa.launchpad.net vivid/main Translation-en
Err http://ppa.launchpad.net vivid/main amd64 Packages
  404  Not Found
Ign http://ppa.launchpad.net vivid/main Translation-en_US
Ign http://ppa.launchpad.net vivid/main Translation-en
Err http://ppa.launchpad.net vivid/main amd64 Packages
  404  Not Found
Ign http://ppa.launchpad.net vivid/main Translation-en_US
Ign http://ppa.launchpad.net vivid/main Translation-en
W: Failed to fetch http://ppa.launchpad.net/chris-lea/python-chardet/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/chris-lea/python-requests/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
 * ERROR: Failed to run install_ubuntu_stable_deps()!!!
```

**Comment by jdowning** [comment]
Same here, but with Utopic. Chris Lea's PPA repos do not have packages for the latest Ubuntu versions. `pythonr-requests` and `python-chardet` have no builds for utopic or vivid: https://launchpad.net/~chris-lea/+archive/ubuntu/python-requests?field.series_filter=utopic

```
W: Failed to fetch http://ppa.launchpad.net/chris-lea/python-chardet/ubuntu/dists/utopic/main/binary-amd64/Packages: 404  Not Found [IP: 91.189.95.83 80]
W: Failed to fetch http://ppa.launchpad.net/chris-lea/python-requests/ubuntu/dists/utopic/main/binary-amd64/Packages: 404  Not Found [IP: 91.189.95.83 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
E: Couldn't rebuild package cache
```

**Comment by DavidJFelix** [comment]
I don't understand why this is even being used... the version in utopic and vivid should be newer than the chris lea archive.

**Comment by s0undt3ch** [comment]
Could you please test the latest development version to confirm the fix?

**Comment by mickadoo** [comment]
Should this have been fixed in develop? I'm still new to salt but running 

```
curl -o /tmp/salt-bootstrap.sh https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh
sudo bash /tmp/bootstrap_salt.sh -P
```

From a VM running vivid still results in this error for me

```
W: Failed to fetch http://ppa.launchpad.net/chris-lea/python-chardet/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/chris-lea/python-requests/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
 * ERROR: Failed to run install_ubuntu_stable_deps()!!!
```

**Comment by oldskool** [comment]
I'm also still having this problem, despite the update in https://github.com/dmick/salt-bootstrap/commit/7ece1993d83db0dd2395d570782e4321b98b8d17

**Comment by DavidJFelix** [comment]
Just stating for the record: My solution was to not use salt-bootstrap. It's a complex bash script and if it's not going to consistently work, I can't afford to base my work on it. I was able to replace it in my workflow with 4 individual scripts per platform which were each < 10 LOC.

**Comment by s0undt3ch** [comment]
Yes, it is a complex script which tries to handle many scenarios in many distributions, but I'm glad you could get around this latest breakage.

**Comment by DavidJFelix** [comment]
No, you misunderstood. My workaround was that I'm not using salt-bootstrap any more. I'm manually bootstrapping it myself using distro-specific install instructions listed in the wiki.

**Comment by s0undt3ch** [comment]
Yes, I did understand :smile:
