### ISSUE TITLE
Problems installing on SLES 12

### ISSUE THREAD

**Issue by cetanu** [saltstack/salt-bootstrap#714]
Hi all,
### What was attempted

Created a new server in AWS using `salt-cloud`, with the image `ami-b90e6283` which is SLES 12.
### Result

salt-cloud was able to do everything except bootstrap salt because of `No dependencies installation function found.`
### How I went about fixing it manually

I had to manually follow the steps here:  
https://docs.saltstack.com/en/latest/topics/installation/suse.html#suse-linux-enterprise

```
zypper addrepo http://download.opensuse.org/repositories/devel:languages:python/SLE_12/devel:languages:python.repo
zypper refresh
zypper install salt salt-minion
```
### Other install steps needed

I think at some point, some packages were half-way through install and failed during the initial cloud bootstrap, so I had to perform the following steps:
1. had to install `python3` and `pip` using `zypper` if they weren't already there.
2. had to install `singledispatch` using `pip` with `--upgrade` flag.  
3. had to install `backports_abc` with `pip.  

After that, I ran salt-minion and it was fine, except things like the hostname had not been set by the bootstrap process, and the minion key came up as `ip-[redacted].ap-southeast-2.compute.internal` on the master when `salt-key -L` was checked.

**Comment by aboe76** [comment]
@cetanu The python-singledispatch en python-backports_abc is fixed within the devel:languages:python repo, and should work, problem was within the python-tornado package, which didn't have the new depencies, and both packages weren't ready in the repo.

please test it again and see if everything is fixed.

(ps, I'm the package maintainer for openSuse and help out with the sles packaging)

**Comment by cetanu** [comment]
No dice I'm afraid.

```
[centos@ip-10-70-0-10 ~]$ sudo salt-cloud -p vsy-suse-micro 714_1
/usr/lib/python2.7/site-packages/salt/config/__init__.py:2241: DeprecationWarning: The term 'provider' is being deprecated in favor of 'driver'. Support for 'provider' will be removed in Salt Nitrogen. Please convert your cloud provider configuration files to use 'driver'.
[INFO    ] salt-cloud starting
[INFO    ] Creating Cloud VM 714_1 in ap-southeast-2
[INFO    ] Attempting to look up root device name for image id ami-b90e6283 on VM 714_1
[INFO    ] Found root device name: /dev/sda1
[INFO    ] Created node 714_1
[INFO    ] Salt node data. Private_ip: 10.70.0.43
[INFO    ] Salt interface set to: 10.70.0.43
Warning: Permanently added '10.70.0.43' (ECDSA) to the list of known hosts.
Mon Jan 11 10:33:21 UTC 2016
[INFO    ] Rendering deploy script: /etc/salt/cloud.deploy.d/bootstrap-salt.sh
Warning: Permanently added '10.70.0.43' (ECDSA) to the list of known hosts.
Mon Jan 11 10:33:23 UTC 2016
Warning: Permanently added '10.70.0.43' (ECDSA) to the list of known hosts.
Connection to 10.70.0.43 closed.
Warning: Permanently added '10.70.0.43' (ECDSA) to the list of known hosts.
Connection to 10.70.0.43 closed.
Warning: Permanently added '10.70.0.43' (ECDSA) to the list of known hosts.
Connection to 10.70.0.43 closed.
Warning: Permanently added '10.70.0.43' (ECDSA) to the list of known hosts.
Connected to 10.70.0.43.
sftp> put  /tmp/tmp_QcHzF /tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457/minion.pem
Uploading /tmp/tmp_QcHzF to /tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457/minion.pem
/tmp/tmp_QcHzF                                100% 1674     1.6KB/s   00:00
Warning: Permanently added '10.70.0.43' (ECDSA) to the list of known hosts.
Connection to 10.70.0.43 closed.
Warning: Permanently added '10.70.0.43' (ECDSA) to the list of known hosts.
Connected to 10.70.0.43.
sftp> put  /tmp/tmp3ycpDi /tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457/minion.pub
Uploading /tmp/tmp3ycpDi to /tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457/minion.pub
/tmp/tmp3ycpDi                                100%  450     0.4KB/s   00:00
Warning: Permanently added '10.70.0.43' (ECDSA) to the list of known hosts.
Connected to 10.70.0.43.
sftp> put  /tmp/tmp_68BuZ /tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457/grains
Uploading /tmp/tmp_68BuZ to /tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457/grains
/tmp/tmp_68BuZ                                100%   16     0.0KB/s   00:00
Warning: Permanently added '10.70.0.43' (ECDSA) to the list of known hosts.
Connected to 10.70.0.43.
sftp> put  /tmp/tmpXD0OB2 /tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457/minion
Uploading /tmp/tmpXD0OB2 to /tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457/minion
/tmp/tmpXD0OB2                                100% 4516     4.4KB/s   00:00
Warning: Permanently added '10.70.0.43' (ECDSA) to the list of known hosts.
Connected to 10.70.0.43.
sftp> put  /tmp/tmp8JnJqF /tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457/deploy.sh
Uploading /tmp/tmp8JnJqF to /tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457/deploy.sh
/tmp/tmp8JnJqF                                100%  205KB 204.5KB/s   00:00
Warning: Permanently added '10.70.0.43' (ECDSA) to the list of known hosts.
Connection to 10.70.0.43 closed.
Warning: Permanently added '10.70.0.43' (ECDSA) to the list of known hosts.
 *  INFO: /bin/sh /tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457/deploy.sh -- Version 2015.08.06
Connection to 10.70.0.43 closed.

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.12.28-4-default
 *  INFO:   Distribution: sles 12

 *  INFO: Installing minion
 *  INFO: Found function config_salt
 *  INFO: Found function daemons_running
 * ERROR: No dependencies installation function found. Exiting...
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /home/centos/.ssh/id_rsa -p 22 ec2-user@10.70.0.43 'sudo /tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457/deploy.sh -c '"'"'/tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457'"'"' git develop'' failed. Exit code: 1
```

I then ssh'd into the machine, ran a `zypper update`, then tried `zypper install salt-minion`, but still doesn't work without adding the repo as above

**Comment by aboe76** [comment]
in the last line:

```
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /home/centos/.ssh/id_rsa -p 22 ec2-user@10.70.0.43 'sudo /tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457/deploy.sh -c '"'"'/tmp/.saltcloud-da374818-adb6-4b60-9354-b3fe96564457'"'"' git develop'' failed. Exit code: 1
```

why install salt from git develop??

should be ok when just running default salt-bootstrap.sh...

**Comment by cetanu** [comment]
Same deal without git args:

```
 *  INFO: /bin/sh /tmp/.saltcloud-d5f4b751-e9c1-46c9-9bc4-67d79ea80e80/deploy.sh -- Version 2015.08.06

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.12.28-4-default
 *  INFO:   Distribution: sles 12

 *  INFO: Installing minion
 *  INFO: Found function config_salt
 *  INFO: Found function daemons_running
 * ERROR: No dependencies installation function found. Exiting...
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /home/centos/.ssh/id_rsa -p 22 ec2-user@10.70.0.134 'sudo /tmp/.saltcloud-d5f4b751-e9c1-46c9-9bc4-67d79ea80e80/deploy.sh -c '"'"'/tmp/.saltcloud-d5f4b751-e9c1-46c9-9bc4-67d79ea80e80'"'"''' failed. Exit code: 1
```

Ran with debug, no new information was output.

I've now just checked my bootstrap script, and it's from 3/sep/2015, so I've downloaded the latest boostrap file and testing again...... and the same result.

To be clear, at this point I don't think it's related to single-dispatch or any of those pip installs that I had to do.  
It seems to be that repo that I need to add. I don't think the bootstrap script takes it into account. I'm going to dig around tomorrow to see where this repo add should be included.

**Comment by vutny** [comment]
@cetanu There were some improvements for bootstrapping Suse systems in `develop` branch recently.
Please try again to fetch latest bootstrap script using command:

``` sh
salt-cloud -u
```

I guess that it should resolve your issues.

**Comment by cetanu** [comment]
Tried again with the following:

```
salt-cloud -u
salt-cloud -p <my suse profile> <name>  # with ami-b90e6283
salt-cloud -p <my suse profile> <name>  # with ami-b90e6283 & args: git develop
salt-cloud -p <my suse profile> <name>  # with ami-0f510a6c
salt-cloud -p <my suse profile> <name>  # with ami-0f510a6c & args: git develop
```

All failed with the same error:

```
 * ERROR: No dependencies installation function found. Exiting...
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /home/centos/.ssh/id_rsa -p 22 ec2-user@10.70.0.32 'sudo /tmp/.saltcloud-f5b0922c-9718-411d-97ca-060c1dcb434b/deploy.sh -c '"'"'/tmp/.saltcloud-f5b0922c-9718-411d-97ca-060c1dcb434b'"'"' git develop'' failed. Exit code: 1
```

**Comment by vutny** [comment]
@cetanu Yeah, `salt-cloud -u` will not work as I figured out recently.
Try this on your host with`salt-cloud` installed:

```
salt-call config.gather_bootstrap_script 'https://bootstrap.saltstack.com/develop/bootstrap-salt.sh'
```

Or:

```
curl -L 'https://bootstrap.saltstack.com/develop' > /etc/salt/cloud.deploy.d/bootstrap-salt.sh
```

There was a documentation update and it should appear on the site soon.

**Comment by vutny** [comment]
@cetanu Does those commands work for you? Thanks for any feedback!

**Comment by cetanu** [comment]
Hello @vutny ,

Still no luck.

I'm using the following profile:

```
<profile name>:
  provider: <provider name>
  image: ami-b90e6283
  size: t2.micro
  ssh_username: ec2-user
  script: bootstrap-salt
  minion:
    master: <master ip>
```

ran the above commands and got the same error as above, but I can ssh into the machine and install the packages with zypper :\

**Comment by vutny** [comment]
@cetanu Sad to hear that.
As a last resort, could you please try to re-run bootstrap script manually on the instance?
Like this:

``` console
sudo /tmp/.saltcloud-f5b0922c-9718-411d-97ca-060c1dcb434b/deploy.sh -D stable
```

This will help to identify on which step it was failed exactly.

P.S. Installing from `git develop` could be possibly broken...

**Comment by cetanu** [comment]
That installed a whole bunch of python modules, but then got stuck with this error:

```
 * DEBUG: Checking if service salt-minion is enabled
 * DEBUG: Service salt-minion is NOT enabled
 * ERROR: Failed to run install_suse_check_services()!!!
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
```

**Comment by vutny** [comment]
Hmm... Looks like an `systemd` related issue to me. Unfortunately, I didn't work closely with SUSE, so can't be sure. @cetanu Have you run bootstrap with `stable` installation type?

**Comment by jfindlay** [comment]
@cetanu, I am able to bootstrap both SLES 11 and SLES 12 on AWS with the latest version of bootstrap.  Can you try using the develop version of bootstrap?

**Comment by cetanu** [comment]
Can you let me know of a public SLES12 AMI that you have used to do this? I've tried at least 3, standard install, git install, develop version, updated bootstrap script, rinse and repeat, and still no luck.

**Comment by jfindlay** [comment]
@cetanu, I've tested with [ami-7f2e6015](https://aws.amazon.com/marketplace/pp/B007O0H35O/) and [ami-48b63120](https://aws.amazon.com/marketplace/pp/B00PMM99PI/).  What is the debug (`-D`) bootstrap output you're getting with the latest bootstrap release, or the develop version?

**Comment by shorawitz** [comment]
I just tested using "suse-sles-12-v20141023-pv-ssd-x86_64 (ami-c5440af5)" with salt-cloud on 2015.8.8.2 and I'm getting:

```
System management is locked by the application with pid 1612 (zypper).
Close this application before trying again.
 * ERROR: Failed to run install_suse_12_stable_deps()!!!
Error: There was a profile error: Command 'ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -i /etc/salt/dchristensen-test.pem -p 22 ec2-user@172.31.21.121 \'sudo /tmp/.saltcloud-188a2c5f-bcd0-4802-bbc3-cb59cd395e3b/deploy.sh -c \'"\'"\'/tmp/.saltcloud-188a2c5f-bcd0-4802-bbc3-cb59cd395e3b\'"\'"\'\'' failed. Exit code: 1
```

**Comment by techhat** [comment]
I am currently experiencing this issue with SLES12SP2 in Azure ARM.

**Comment by rallytime** [comment]
#1075 might have helped with this one. It fixes an issue that had a similar problem with the services starting. However it doesn't address the last error you posted about not installing the deps. The fix in #1075 is available in the latest stable release of the bootstrap script.
