### ISSUE TITLE
python-futures is not installed with a git bootstrap install

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-bootstrap#917]
### Description of Issue/Question

When attempting to bootstrap an ubuntu 14 minion I noticed it did not install python-futures which is a dependency of the tcp transport.
### Setup
1. ubuntu14 
2. `wget -O bootstrap.sh https://bootstrap.saltstack.com`
### Steps to Reproduce Issue
1. `sh bootstrap.sh -M -P git v2015.8.1`

```
root@ubuntu:~# dpkg -l | grep -i future
root@ubuntu:~# 

root@ubuntu:~# pip list | grep -i future
root@ubuntu:~# 
```

And when I attempt to add `transport: tcp` to the master/minion config I receive the following error when running an execution module:

```
root@ubuntu:~# salt '*' test.ping                                                                                                                                                                                  
Exception AttributeError: "'SaltMessageClient' object has no attribute '_closing'" in <bound method SaltMessageClient.__del__ of <salt.transport.tcp.SaltMessageClient object at 0x7fed3c2e9150>> ignored
Exception AttributeError: "'AsyncTCPReqChannel' object has no attribute 'message_client'" in <bound method AsyncTCPReqChannel.__del__ of <salt.transport.tcp.AsyncTCPReqChannel object at 0x7fed3c2d7f50>> ignored
No module named concurrent.futures
```

This is related to the following issue: https://github.com/saltstack/salt-pack/issues/96 Looks like they ran into the same issue and this has been fixed in the packages for repo.saltstack.com but needs to be fixed for the bootstrap git install.
### Versions and Systems

```
root@ubuntu:~# salt --versions-report
Salt Version:
           Salt: 2015.8.11

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.4
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.5.5-x86_64-linode69
         system: Ubuntu 14.04 trusty
```

**Comment by rallytime** [comment]
@Ch3LL This is fixed with #936, which is available in the latest version of salt-bootstrap, v2016.08.16:

```
root@rally-u14:~# sh bootstrap.sh -v
bootstrap.sh -- Version 2016.08.16
root@rally-u14:~# sh bootstrap.sh -M -P git v2015.8.11
 *  INFO: Running version: 2016.08.16
 *  INFO: Executed by: sh
 *  INFO: Command line: 'bootstrap.sh -M -P git v2015.8.11'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.4.0-34-generic
 *  INFO:   Distribution: Ubuntu 14.04

 *  INFO: Installing minion
 *  INFO: Installing master
 *  INFO: Found function install_ubuntu_git_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_ubuntu_git
 *  INFO: Found function install_ubuntu_git_post
 *  INFO: Found function install_ubuntu_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_ubuntu_check_services
 *  INFO: Running install_ubuntu_git_deps()
<snipped>
 *  INFO: Running install_ubuntu_git_post()
 *  WARN: Upstart does not appear to know about salt-minion
 *  WARN: Upstart does not appear to know about salt-master
 *  WARN: Upstart does not appear to know about salt-api
 *  INFO: Running install_ubuntu_check_services()
 *  INFO: Running install_ubuntu_restart_daemons()
salt-minion start/running, process 3422
salt-master start/running, process 3427
 *  INFO: Running daemons_running()
 *  INFO: Salt installed!
```

Also note that the bootstrap script has been refactored so that the `-P` is no longer necessary when installing on Ubuntu by default, as we are already packaging all of the necessary deps at repo.saltstack.com.

**Comment by frogunder** [comment]
This is still an issue on CentOS 7.

```
[root@li1193-121 ~]# salt --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 4.6.3-x86_64-linode70
         system: Linux
        version: CentOS Linux 7.0.1406 Core
```

```
[root@li1193-121 ~]# pip list | grep -i future
[root@li1193-121 ~]# 
```

```
[root@li1193-121 ~]# sh bootstrap.sh -v
bootstrap.sh -- Version 2016.08.16
```

 add `transport: tcp` to the master/minion config

```
[root@li1193-121 ~]# salt \* test.ping
Exception AttributeError: "'SaltMessageClient' object has no attribute '_closing'" in <bound method SaltMessageClient.__del__ of <salt.transport.tcp.SaltMessageClient object at 0x3599090>> ignored
Exception AttributeError: "'AsyncTCPReqChannel' object has no attribute 'message_client'" in <bound method AsyncTCPReqChannel.__del__ of <salt.transport.tcp.AsyncTCPReqChannel object at 0x35990d0>> ignored
No module named concurrent.futures
```
